name: Codeception tests

on: [push]

jobs:
  build:
    name: ${{matrix.operating-system}}, PHP ${{ matrix.php }}

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ ubuntu-latest, ubuntu-20.04 ]
        php: [ '8.0', '8.1' ]

    steps:
      - uses: actions/checkout@master

      - name: Setup PostgreSQL
        run: |
          sudo systemctl start postgresql.service
          psql -c 'CREATE DATABASE kodus_db_cache_test;' -U postgres -h localhost

      - name: Setup MySQL
        run: |
          sudo systemctl start mysql.service
          mysql -e 'CREATE DATABASE kodus_db_cache_test;'

      - name: Setup PHP
        uses: nanasess/setup-php@master
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: php vendor/bin/codecept run
